### PR TITLE
add wait and flush for matutils command

### PR DESCRIPTION
**Pull request by gholden3**
- wait for result of matmul command
- call flush after that
- use https vs http where possible
- use snake case in python

### CODE REVIEW

**Comment by gholden3** [comment]
@joshuailevy  what I'm not sure about is how to test this. How could I take my branch and "conda-ize" it so i can see if it fixes the problem with the lineages file?

**Comment by joshuailevy** [comment]
Awesome, thanks for adding this in! Are you able to use ```pip install -e .``` (when executing from the Freyja repo)? That should hopefully do the trick.

**Comment by gholden3** [comment]
> Awesome, thanks for adding this in! Are you able to use `pip install -e .` (when executing from the Freyja repo)? That should hopefully do the trick.

Thanks! I'm running into this error: 

(base) ➜  Freyja git:(gholden/lineage_tree) pip install -e

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

-e option requires 1 argument

**Comment by joshuailevy** [comment]
I think you need to specify the directory after the ```-e```, but then it should hopefully run properly! That is, you'll want ```pip install -e [your-freyja-repo-directory]```. I generally use ```pip install -e .``` since the command is run from within the directory.

**Comment by gholden3** [comment]
found this interesting question btw https://stackoverflow.com/questions/43358019/python-subprocess-call-not-waiting-for-process-to-finish-blender

**Comment by gholden3** [comment]
@joshuailevy  I verified this new code works fine on my mac. Given that stackoverflow above, I'd like to also test on another OS tomorrow.

**Comment by joshuailevy** [comment]
That's awesome. I'll try to make some time to pull this PR and test it out on my end in the next day or so!

**Comment by gholden3** [comment]
Thanks. Question for you, if we fail to run the matutils command successfully, should we just exit the script? or is it worth just logging the error and trying to continue?

**Comment by joshuailevy** [comment]
Good q. The script should probably be exited, as many of the later components of the script depend on the results of that command. Thanks again for pushing this forward!

**Comment by gholden3** [comment]
Sounds good. Yeah I think that will help with debugging too because I suspect the missing lineage file is related to some error or another happening with the matUtils command, which is being ignored, as opposed to actually some issue writing the file out.

**Comment by gholden3** [comment]
HI Josh, 
I tried a bit today but I actually don't have an easy way to test this change on another operating system. Are you able to test this on your end? Another thing we could potentially do to test is package up a conda and try to run that. Let me know if you have any further thoughts on the PR!

**Comment by gholden3** [comment]
Also, I noticed this lineages issue #90 seems to happen more frequently in low memory environments. I still think we should implement the fix in this PR though, because it will improve the error handling, by logging the error right away if matutils fails, not waiting until the next step when we try to open the lineages file.

**Comment by joshuailevy** [comment]
Yeah, now that the global tree is as big as it is, the barcoding operation can cause things to break in low memory environments (plan is to instead host up-to-date barcodes on the freyja repo, but I need to carve out some time for that). 

And I'll test this out on a linux machine tonight or tomorrow morning! Sorry for the delay. 
Josh

**Comment by gholden3** [comment]
Thats a great idea. Do let us know when you make that change. We're running the freyja conda package in a secure environment and we would need to add any new network endpoints, such as the freyja repo, to the firewall rules. No rush on the fix, I was able to get consistent results by bumping memory. I do think it will help improve the error handling to do this though.

**Comment by joshuailevy** [comment]
Opened a separate PR for this, closing.

**Pull request closed without merging**
